group: forge
steps:
  - name: forge
    wanda: .buildkite/forge.wanda.yaml

  - name: hello
    wanda: .buildkite/hello.wanda.yaml
    depends_on: forge
  
  - name: hello test
    depends_on: hello
    job_env: hello
    command: cat /opt/app/hello.txt

  - name: python-base
    label: python {{matrix}}
    wanda: .buildkite/python.wanda.yaml
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
    env:
      PYTHON_VERSION: "{{matrix}}"

  - name: forge-arm64
    wanda: .buildkite/forge-arm64.wanda.yaml
    instance_type: builder-arm64
