group: forge
steps:
  - name: forge
    wanda: .buildkite/forge.wanda.yaml

  - name: hello
    tags: wanda
    wanda: .buildkite/hello.wanda.yaml
    depends_on: forge

  - name: hello test
    tags: wanda
    depends_on: hello
    job_env: hello
    command: cat /opt/app/hello.txt

  - name: retry test
    tags: wanda
    depends_on: hello
    job_env: hello
    command: if [[ "$${BUILDKITE_RETRY_COUNT-0}" == 0 ]]; then exit 1; fi

  - name: python-base
    tags: wanda
    label: python {{matrix}}
    wanda: .buildkite/python.wanda.yaml
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
    env:
      PYTHON_VERSION: "{{matrix}}"

  - name: forge-arm64
    wanda: .buildkite/forge-arm64.wanda.yaml
    instance_type: builder-arm64

  - name: artifact-test
    tags:
      - wanda
      - raycicmd
    wanda: .buildkite/artifact-test.wanda.yaml
