group: macos
sort_key: "~macos"
steps:
  - name: ":macos: apple silicon macos example"
    job_env: MACOS
    instance_type: macos-arm64
    commands: 
      - echo "Hello, MacOS arm64!"

  - block: "Run Intel MacOS Tests"

  - name: ":macos: intel silicon macos example"
    job_env: MACOS
    instance_type: macos
    commands: 
      - echo "Hello, MacOS!"
