group: macos
sort_key: "~macos"
steps:
  - block: "Run Apple Silicon MacOS Tests"
    key: "macos-apple-silicon-block"

  - name: ":macos: apple silicon macos example"
    job_env: MACOS
    instance_type: macos-arm64
    depends_on: "macos-apple-silicon-block"
    commands: 
      - echo "Hello, MacOS arm64!"

  - block: "Run Intel MacOS Tests"
    key: "macos-intel-block"

  - name: ":macos: intel silicon macos example"
    job_env: MACOS
    instance_type: macos
    depends_on: "macos-intel-block"
    commands: 
      - echo "Hello, MacOS!"
