group: macos
steps:
  - name: ":macos: macos example"
    job_env: MACOS
    instance_type: macos
    commands: 
      - echo "Hello, MacOS!"

  - name: ":macos: macos example"
    job_env: MACOS
    instance_type: macos-arm64
    commands: 
      - echo "Hello, MacOS arm64!"
  
  - block: "run additional mac tests"

  - name: ":macos: another macos example"
    job_env: MACOS
    instance_type: macos
    commands: 
      - echo "Hello, MacOS again!"
