steps:
  - label: "legacy ray_ci python test"
    commands:
      - yum install -y python3
      - pip3 install pytest click pyyaml
      - (cd ray_ci; python3 -m pytest -v .)
    plugins:
      - docker#v5.7.0:
          image: amazonlinux:2
          shell: ["/bin/bash", "-elic"]
    agents:
      queue: "runner_queue_pr"
  - label: "rayci go tests"
    commands:
      - go test -v ./...
    agents:
      queue: "runner_queue_pr"
    plugins:
      - docker#v5.7.0:
          image: "golang:1.20.5-bookworm"
  - label: "test rayci with rayci"
    commands:
      - RAYCI_BRANCH="$${BUILDKITE_COMMIT}" /bin/bash run_rayci.sh -upload
