steps:
  - label: "ray_ci test"
    commands:
      - yum install -y python3
      - pip3 install pytest click pyyaml
      - (cd ray_ci; python3 -m pytest -v .)
    plugins:
      - docker#v5.7.0:
          image: amazonlinux:2
          shell: ["/bin/bash", "-elic"]
    agents:
      queue: "runner_queue_branch"
