steps:
  - label: ":test_tube: Validate test rules"
    commands:
      - RAYCI_BRANCH="$${BUILDKITE_COMMIT}" /bin/bash run_rayci.sh test-rules
    agents:
      queue: "runner_queue_small_pr"

  - label: "test rayci with rayci"
    commands:
      - RAYCI_BRANCH="$${BUILDKITE_COMMIT}" /bin/bash run_rayci.sh -upload
    agents:
      queue: "runner_queue_small_pr"
