steps:
  - label: "ray_ci test"
    commands:
      - pip install pytest click pyyaml
      - (cd ray_ci; pytest -v .)
    plugins:
      - docker#v5.7.0
          image: amazonlinux:2023
          shell: ["/bin/bash", "-elic"]
    agents:
      queue: "runner_queue_branch"
