group: release
steps:
  # Use release queue to build rayci and wanda release binaries.
  # This makes sure that the release queue is working and also
  # builds the releases and save the binaries in build artifacts.
  - name: rayci and wanda binaries
    tags:
      - wanda
      - raycicmd
    instance_type: release
    commands:
      - pip install uv
      - export PATH="$(python -m site --user-base)/bin:$PATH"
      - bash release.sh
      - cp _release/* /artifact-mount
    depends_on: forge
