group: go tests
steps:
  - label: Go tests
    command: go test ./...
    queue: small
    depends_on: forge
  - label: Go fmt
    command:
      - go fmt ./...
      - git diff --exit-code
    queue: small
    depends_on: forge
  - label: Python {{matrix}} tests
    command:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 029272617770.dkr.ecr.us-west-2.amazonaws.com
      - export IMAGE=$$RAYCI_WORK_REPO:$$RAYCI_BUILD_ID-wanda-py{{matrix}}
      - echo $$IMAGE
      - docker run -ti --rm $$IMAGE python --version
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
    depends_on:
      - python-base
      - forge
  - label: "Failing test"
    tags: disabled
    command: exit 1
