group: go tests
steps:
  - label: Go tests
    tags:
      - wanda
      - raycicmd
      - raycirun
      - reefd
    command: WANDA_TEST_CR_PORT=5555 go test ./...
    queue: small
    docker_publish_tcp_ports: "5555"
    depends_on: forge
  - label: Go arm64 tests
    tags:
      - wanda
      - raycicmd
      - raycirun
      - reefd
    command: WANDA_TEST_CR_PORT=5555 go test ./...
    job_env: forge-arm64
    queue: medium-arm64
    docker_publish_tcp_ports: "5555"
    depends_on: forge-arm64

  - label: Go fmt
    tags: lint
    command:
      - go fmt ./...
      - git diff --exit-code
    queue: small
    depends_on: forge

  - label: Python {{matrix}} tests
    tags: wanda
    command:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 029272617770.dkr.ecr.us-west-2.amazonaws.com
      - export IMAGE=$$RAYCI_WORK_REPO:$$RAYCI_BUILD_ID-wanda-py{{matrix}}
      - echo $$IMAGE
      - docker run -ti --rm $$IMAGE python --version
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
    depends_on:
      - python-base
      - forge
  - label: Wanda wheel tests
    tags: wanda
    command:
      - pip install uv
      - export PATH="$(python -m site --user-base)/bin:$PATH"
      - cd wheels/wanda
      - uv run build_wheels.py --platform linux-amd64 --output-dir dist
      - uv run pytest build_wheels_test.py -v
      # Smoke test: install wheel and verify binary runs
      - pip install dist/*.whl
      - wanda --help
    queue: small
    depends_on: forge

  - label: "Failing test"
    tags: disabled
    command: exit 1
