group: go tests
steps:
  - label: Go tests
    command: go test ./...
    queue: small
    depends_on: forge
  - label: Go fmt
    command:
      - go fmt ./...
      - git diff --exit-code
    queue: small
    depends_on: forge
  - label: Python {{matrix}} tests
    command: "docker run --rm $$RAY_CI_WORKREPO:$$RAYCI_BUILD_ID-wanda-py{{matrix}} python --version"
    matrix:
      - "3.9"
      - "3.10"
      - "3.11"
    depends_on:
      - python-base
      - forge
