group: windows
steps:
  - name: ":windows: windows example"
    job_env: WINDOWS
    instance_type: windows
    commands: 
      - bash .buildkite/windows_docker.sh
      - /c/tools/docker/docker ps
      - echo "Hello, Windows!"
